### ISSUE TITLE
VS2017 15.3 emits C7510 with /permissive- (use of dependent template name must be prefixed with 'template')

### ISSUE THREAD

**Issue by JayhawkZombie** [rttrorg/rttr#183]
[MSVC 15.3 partially supports two-phase lookup](https://blogs.msdn.microsoft.com/vcblog/2017/09/11/two-phase-name-lookup-support-comes-to-msvc/), and now enforces the requirement that the use of dependent names must be prefixed with 'template'.  Their implementation is not perfect, though, and will sometimes emit invalid errors

Only 1 file generated these errors, `rttr/detail/registration/bind_impl.hpp`

On lines [358](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L358), [388](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L388), [449](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L449), [477](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L477), [539](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L539), [566](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L566), [625](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L625), [678](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L678), [698](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L698), [778](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L778), and [783](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L783), the `get` in `type::get<ClassType>` can be prefixed with `template`, like `type::template get<ClassType>`, to silence the error. 

From their article, it seems invalid errors are emitted with local non-type dependent expressions, but I'm not sure these would be a result of that compiler bug.  In any case, I don't have other compilers to test the changes on.  If it is only a VS2017 issue, then at least others who get the errors may see this and have the changes needed to fix the errors.

**Comment by acki-m** [comment]
@JayhawkZombie 
Please provide a PR to fix the issue

**Comment by vamidi** [comment]
on Visual studio 15.8.3, I got the same error on all those lines as well adding `type::template get<ClassType>` indeed fixes the error

**Comment by JayhawkZombie** [comment]
Sorry, I didn’t see the responses. I will open a pull request soon that fixes the issue.

**Comment by vamidi** [comment]
Sure thing no problem!

**Comment by acki-m** [comment]
@JayhawkZombie 
with 15.8.5 I don't get any of these errors. Is a PR still needed?

**Comment by Vennor** [comment]
This still happens for me on 15.9.4 with `/permissive-` and two-phase lookup turned on, but this time it's only tied do `type::get` calls. Should I fix it?

**Comment by CosmicRey** [comment]
I believe this issue is resolved with PR https://github.com/rttrorg/rttr/pull/216 merged in, could you verify?

**Comment by Vennor** [comment]
To begin with I apologise for taking a long time on this. At the moment this still happens on VS 16.3.9 and rttr 0.9.6-1. Nevertheless, I see that the current master `bind_impl.hpp` already has greatly reduced `type::get` call count and the remaining ones are properly decorated with the `template` keyword, so I assume a fix is coming in the next release.

**Comment by paulhazen** [comment]
> On lines [358](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L358), [388](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L388), [449](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L449), [477](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L477), [539](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L539), [566](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L566), [625](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L625), [678](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L678), [698](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L698), [778](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L778), and [783](https://github.com/rttrorg/rttr/blob/master/src/rttr/detail/registration/bind_impl.h#L783), the `get` in `type::get<ClassType>` can be prefixed with `template`, like `type::template get<ClassType>`, to silence the error.
> 
@JayhawkZombie - Silencing the error in this manner causes very hard to track down problems: See my closed issue #292. Putting this note here in case anybody makes the same mistake as I did.

**Comment by OneMeanDragon** [comment]
this fix also removed the requirement for "/permissive" good catch
also dont forget to at LN: 39 "flat_map.h"
`
//#include <ciso646> // _LIBCPP_VERSION
`
noticed on the ms issues board.
