### ISSUE TITLE
LNK2001 when using policy in my code.

### ISSUE THREAD

**Issue by traveller59** [rttrorg/rttr#77]
Environment: visual studio 2017, RTTR master library built by msvc 15.0
When I'm using policy such as policy::ctor::as_object, I get a error: 
**LNK2001: unresolved external symbol "public: static struct rttr::detail::as_object const rttr::policy::ctor::as_object" (?as_object@ctor@policy@rttr@@2U0detail@3@B)**
If I don't use this class, everything is ok.
Here is my project settings related to RTTR:
config: debug x64
include path: I:\library\cpp\rttr-master-build\include
library path:  I:\library\cpp\rttr-master-build\lib
linker input file: rttr_core_d.lib

**Comment by traveller59** [comment]
This problem is solved by set RTTR dll path at vs2017-project properties-C/C++-preprocessor-preprocessor definition. It's my mistake

**Comment by jzy916789135** [comment]
I tried your method, but still failed. Can I just add a RTTR_DLL to the environment variable?

**Comment by Cccrisppp** [comment]
I tried your method, but still failed. Just add a RTTR_DLL to the environment variable?

**Comment by ray-linn** [comment]
Just right click the project in Visual studio , choose "project properties" , and then "C/C++-preprocessor"   -- > "preprocessor definition" , add the "RTTR_DLL", no require for the DLL PATH.
